include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - prefer_single_quotes
    - require_trailing_commas
